# Generated by Django 3.2.9 on 2025-01-20 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_bill', models.FloatField(default=0)),
                ('sex', models.CharField(max_length=24)),
                ('smoker', models.BooleanField(default=False)),
                ('day', models.CharField(max_length=24)),
                ('time', models.CharField(max_length=24)),
                ('size', models.FloatField(default=0)),
                ('tip', models.CharField(max_length=20)),
            ],
        ),
    ]
